apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: 2020-03-17T05:14:42Z
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: mysql
    component: slave
    heritage: Helm
    release: mysql
  name: data-mysql-slave-0
  namespace: mysql
  resourceVersion: "206368"
  selfLink: /api/v1/namespaces/mysql/persistentvolumeclaims/data-mysql-slave-0
  uid: f0e77d9b-af5a-41ec-9c56-a0929947bc30
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeMode: Filesystem
status:
  phase: Pending
