---
apiVersion: v1
kind: Namespace
metadata:
  name: office
---
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployer
  namespace: office
---
--- 
 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployer-role
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - <list of policies to authorize>
---
--- 
  
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deployer-role-binding
roleRef:
  kind: ClusterRole
  name: deployer-role
  apiGroup: rbac.authorization.k8s.io
subjects:
# Authorize specific service accounts:
- kind: ServiceAccount
  name: deployer
  namespace: office
# Authorize specific users (not recommended):
#- kind: User
#  apiGroup: rbac.authorization.k8s.io
#  name: <authorized user name>
---
---  
  