cat <<EOF | kubectl apply -f -	
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    app: busybox
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
    resources:
      limits:
        memory: "8Gi"
      requests:
        memory: "3Gi"
  restartPolicy: Always
  nodeSelector:
    kubernetes.io/hostname:
      worker1
EOF

	
cat <<EOF | kubectl apply -f -	
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    app: busybox
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
    resources:
      limits:
        cpu: "100"
      requests:
        cpu: "0.8"
  restartPolicy: Always
  nodeSelector:
    kubernetes.io/hostname:
      worker1
EOF