apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: no-privileged-pods-authenticated
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: no-privileged-pods-psp
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: system:authenticated