apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: no-privileged-pods-psp
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - no-privilegd-pods-psp