kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: psp:restricted
  namespace: office
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs: ['use']
  resourceNames:
  - psp-restricted # the psp we are giving access to
---
---
# This applies psp/restricted to all authenticated users
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: psp:restricted
  namespace: office
subjects:
# Authorize all service accounts in a namespace:
#- kind: Group
#  apiGroup: rbac.authorization.k8s.io
#  name: system:serviceaccounts
# Or equivalently, all authenticated users in a namespace:
#- kind: Group
#  apiGroup: rbac.authorization.k8s.io
#  name: system:authenticated
- kind: User
  name: employee
roleRef:
  kind: Role
  name: psp:restricted # A references to the role above
  apiGroup: rbac.authorization.k8s.io
---