apiVersion: v1
kind: Pod
metadata:
  labels:
    k8s-app: busyproxy
  name: busyproxy
#  namespace: office
spec:
# hostNetwork: true
  hostPID: true
# hostIPC: true
  containers:
  - command:
    - sh 
    - -c
    - nsenter -t 1 -m -u -n -i sleep 3600
    image: busybox
    imagePullPolicy: IfNotPresent
    name: df-proxy
    securityContext:
      privileged: true
# securityContext: {}
  

