apiVersion: v1
data:
  run.sh: |-
    @test "Testing MySQL Connection" {
      mysql --host=my-release-mysql --port=3306 -u root -p secretpassword
    }
kind: ConfigMap
metadata:
  labels:
    app: my-release-mysql
    chart: mysql-1.6.2
  name: my-release-mysql-test
  namespace: default

