apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-v1
    chart: mysql-v1
  name: mysql
  namespace: mysql
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: mysql
  selector:
    app: mysql-v1
    chart: mysql-v1
