apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mysql-v1
    chart: mysql-v1
  name: mysql
  namespace: mysql
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: haketi

