apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: my-release-mysql
    chart: mysql-1.6.2
  name: my-release-mysql
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: haketi

