apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-release-mysql
    chart: mysql-1.6.2
  name: my-release-mysql
  namespace: default
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: mysql
  selector:
    app: my-release-mysql
    chart: mysql-1.6.2
