apiVersion: v1
data:
  mysql-password: bXlzcWxwYXNzd29yZA==
  mysql-root-password: bXlzcWxyb290cGFzc3dvcmQ=
kind: Secret
metadata:
  labels:
    app: mysql-v1
    chart: mysql-v1
  name: mysql
  namespace: mysql
type: Opaque
