apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: mysql
    name: mysql
  nfs:
    server: 192.168.205.14
    path: /nfs/kubedata/db/mysql  #Pat should exist on nfs server
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mysql-v1
    chart: mysql-v1
  name: mysql
  namespace: mysql
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeName: "mysql"
  