---
elasticsearchHosts: "http://elasticsearch-master:9200"

replicas: 1

resources:
  requests:
    cpu: "512m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "2Gi"

httpPort: 5601

service:
  type: NodePort
