apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus
  namespace: monitor
spec:
  rules:
  - host: prometheus.dv.kube.io
    http:
      paths:
      - backend:
          serviceName: prometheus
          servicePort: 9090