apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/conf.d/
        - name: certs
          mountPath: /etc/nginx/ssl
      restartPolicy: Always
      volumes:
      - name: certs
        secret:
          secretName: nginxsecret
      - name: config
        configMap:
          name: nginx-default-conf
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginxsvc
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: ClusterIP
---



















