apiVersion: v1
kind: Namespace
metadata:
  name: db-redis
---
---  
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: db-redis
  labels:
    app: redis  
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      name: redis
  clusterIP: None
  selector:
    app: redis      
---
---      
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: db-redis
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - env:
        - name: REDIS_PASSWORD
          value: awe345
        image: redis:6.0
        imagePullPolicy: IfNotPresent
        name: redis
        ports:
        - containerPort: 6379
          name: redis
          protocol: TCP
        securityContext:
          runAsUser: 1001
        volumeMounts:
        - mountPath: /data
          name: redis-data
      securityContext:
        fsGroup: 1001 
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      labels:
        app: redis
      name: redis-data
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 1Gi
      storageClassName: nfs-storageclass
      volumeMode: Filesystem
---
---