apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
    chart: mysql
  name: mysql
  namespace: mysql-stateful
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: mysql
  selector:
    app: mysql
    chart: mysql