apiVersion: v1
data:
  mysql-password: bXlzcWxwYXNzd29yZA==
  mysql-root-password: bXlzcWxyb290cGFzc3dvcmQ=
kind: Secret
metadata:
  labels:
    app: mysql
    chart: mysql
  name: mysql
  namespace: mysql-stateful
type: Opaque
